# Generated by Django 5.2.1 on 2025-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("RECRUITER", "Recruiter"), ("CANDIDATE", "Candidate")],
                default="CANDIDATE",
                max_length=12,
            ),
        ),
    ]
